apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: sopheaktra/config-server:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP

          readinessProbe:
            httpGet:
              path: /config-server/actuator/health
              port: 8888
            initialDelaySeconds: 60
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /config-server/actuator/health
              port: 8888
            initialDelaySeconds: 60
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: staging
spec:
  type: ClusterIP
  selector:
    app: config-server
  ports:
    - name: http
      port: 8888
      targetPort: http
      protocol: TCP